import { Inter } from 'next/font/google'
import { Theme } from '@radix-ui/themes'
import './globals.css'
import Navbar from './components/Navbar'
import '@radix-ui/themes/styles.css';
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body className={inter.className}>
          <link rel="preconnect" href="https://fonts.googleapis.com" />
          <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
          <link href="https://fonts.googleapis.com/css2?family=Inter&family=Poppins:wght@300&family=Work+Sans&display=swap" rel="stylesheet" />
        <Theme>
          <Navbar></Navbar>
          <main className='p-6'>{children}</main>
        </Theme>
      </body>
    </html>
  )
}
